### ISSUE TITLE
Retrieve reply timeout with MST

### ISSUE THREAD

**Issue by fm4d** [ch11ng/xelb#11]
EXWM/XELB is crashing with this error https://gist.github.com/fm4d/a6f2c115f1db275e7a82ac2ef40398fb when I am trying to make my 2 daisy-chained external monitors work via following command.

``` lisp
(add-hook 'exwm-randr-screen-change-hook
     (lambda ()
         (start-process-shell-command
             "xrandr" nil "xrandr --output eDP1 --mode 1920x1080 --output DP1-1 --right-of eDP1 --output DP1-2 --right-of DP1-1")))
```

Xrandr seems to be fine, runniing this command outside of EXWM creates monitor setup as expected.

**Comment by ch11ng** [comment]
Could you insert

``` elisp
(message "EXWM:RANDR:OUTPUT: %s" output)
```

just below Line 72 in exwm-randr.el (`(dolist (output outputs)`) and show me the content of the `*Messages*` buffer together with the output of

``` shell
DISPLAY=:0 xrandr --verbose
```

executed in console?

**Comment by fm4d** [comment]
`EXWM:RANDR:OUTPUT: 67`
https://gist.github.com/fm4d/e9f193c376800aaed780bca3df084efc

**Comment by fm4d** [comment]
I found out that the bug is not present only with the xrandr setup above but with any setup as long as I have DP1.2 / MST enabled on my monitor and I have these two monitors daisy-chained. For example 
`xrandr --output eDP1 --mode 1920x1080 --output DP1-1 --right-of eDP1 --auto --output DP1-2 --off` is also timing out with the same error.

EDIT: After some fight I made it work by not calling xrandr in exwm-randr-screen-change-hook but calling exwm-randr--reset manually after setting xrandr via console ( and having workspace-output-plist set accordingly), I will try to look deeper into exwm-randr code later.

**Comment by ch11ng** [comment]
I can't find any problem from your last Gist.  You first Gist indicates that a `GetOutputInfo` request was failed but the inputs for that request were from a preceding `GetScreenResources` request which should ensure all inputs are valid.  So it's kind of weird.

Besides, which version of Emacs do you use? The RandR code can be problematic on Emacs 24.

**Comment by fm4d** [comment]
25.0.92.1

**Comment by fm4d** [comment]
25.0.92.1

**Comment by ch11ng** [comment]
Or could you insert the following lines at the end of your .emacs:

``` elisp
(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
             "randr-test" nil "date >> ~/randr-test.txt; xrandr --verbose >> ~/randr-test.txt")))
```

and show me the content of ~/randr-test.txt?

**Comment by fm4d** [comment]
https://gist.github.com/fm4d/49a7ae70e8b802aeb7b85392abcae2a2

**Comment by ch11ng** [comment]
Well, there seems to be nothing wrong again.  Considered that you can do the refresh manually, what if you set that hook after EXWM has been initialized?

**Comment by fm4d** [comment]
Actually it is totally incosistent, I am only able to make it work manually IF there is the exwm-randr-screen-change-hook that ends with xelb timeout. I actually have a feeling that xrandr could be the source of the problem, linux is just somehow not prepared for DP1.2 because I also experience weird graphical glitches and blackouts etc.

**Comment by fm4d** [comment]
It seems like I fixed it with xf86-video-modesetting instead of xf86-video-intel so feel free to close this as it really seems to be caused by driver.

**Comment by ch11ng** [comment]
All right, I'm closing it.
