### ISSUE TITLE
Xinerama not working on LTSP thin client

### ISSUE THREAD

**Issue by map7** [ch11ng/xelb#13]
I'm using the git repo for xelb & exwm (as of 29/07/2016) with Emacs 25.0.50.2 on Debian 7 on an LTSP thin client. It loads up on my thin client (which has three screens) and I can tell that xinerama is not binding correctly with xelb as the modeline of emacs spans across all three screens.

Xinerama is loaded

```
    xdpyinfo | egrep -i 'Xinerama|DDC|Reduced Blanking'
    result = XINERAMA
```

Here is my exwm randr setup

```
(setq exwm-randr-workspace-output-plist '(0 "DP1" 1 "HDMI2" 2 "HDMI3"))
(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
             "xrandr" nil "xrandr --output DP1 --right-of HDMI2 --output DP1 --mode 1920x1080 --output HDMI3 --left-of HDMI2 --output HDMI3 --mode 1920x1080")))
(exwm-randr-enable)
```

Here is my .xsession/.xinitrc

```
#!/usr/bin/env bash
# Disable access control
xhost +SI:localuser:$USER

# Fallback cursor
xsetroot -cursor_name left_ptr

# Keyboard repeat rate
#xset r rate 180 40

# Set capslock as ctrl
setxkbmap -layout us -option ctrl:nocaps

# If Emacs is started in server mode, `emacsclient` is a convenient way
# to edit files in place (used by e.g. `git commit`)
export VISUAL=emacsclient
export EDITOR="$VISUAL"

xset b off &
xhost +

exec dbus-launch --exit-with-session emacs
```

**Comment by ch11ng** [comment]
RandR and Xinerama are two different extensions.  EXWM only supports (the more advanced) RandR and what you configured is only RandR.  Please show the output of `xrandr`.

**Comment by map7** [comment]
Screen 0: minimum 320 x 200, current 5760 x 1080, maximum 8192 x 8192
VGA1 disconnected (normal left inverted right x axis y axis)
DP1 connected 1920x1080+3840+0 (normal left inverted right x axis y
axis) 527mm x 296mm
   1920x1080      60.0_\+   50.0     59.9 
   1920x1080i     30.0     25.0     30.0 
   1600x1200      60.0 
   1600x900       60.0 
   1280x1024      75.0     60.0 
   1152x864       75.0 
   1280x720       60.0     50.0     59.9 
   1024x768       75.1     60.0 
   800x600        75.0     60.3 
   720x576        50.0 
   720x480        60.0     59.9 
   640x480        75.0     60.0     59.9 
   720x400        70.1 
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 connected 1920x1080+1920+0 (normal left inverted right x axis y
axis) 480mm x 270mm
   1920x1080      59.9_\+   60.0     50.0     59.9 
   1920x1080i     30.0     25.0     30.0 
   1600x1200      60.0 
   1680x1050      59.9 
   1280x1024      75.0     60.0 
   1440x900       59.9 
   1280x960       60.0 
   1152x864       75.0 
   1280x720       60.0     50.0     59.9 
   1440x576i      25.0     25.0 
   1024x768       75.1     70.1     60.0 
   1440x480i      30.0     30.0 
   832x624        74.6 
   800x600        72.2     75.0     60.3     56.2 
   720x576        50.0 
   720x480        60.0     59.9 
   640x480        75.0     72.8     66.7     60.0     59.9 
   720x400        70.1 
DP2 disconnected (normal left inverted right x axis y axis)
HDMI3 connected 1920x1080+0+0 (normal left inverted right x axis y axis)
480mm x 270mm
   1920x1080      59.9*+   60.0     50.0     59.9 
   1920x1080i     30.0     25.0     30.0 
   1600x1200      60.0 
   1680x1050      59.9 
   1280x1024      75.0     60.0 
   1440x900       59.9 
   1280x960       60.0 
   1152x864       75.0 
   1280x720       60.0     50.0     59.9 
   1440x576i      25.0     25.0 
   1024x768       75.1     70.1     60.0 
   1440x480i      30.0     30.0 
   832x624        74.6 
   800x600        72.2     75.0     60.3     56.2 
   720x576        50.0 
   720x480        60.0     59.9 
   640x480        75.0     72.8     66.7     60.0     59.9 
   720x400        70.1 

Regards,

Michael Pope
Programmer

Digitech Corporation
Ph +61 3 9642 4032

Disclaimer:
This message contains confidential information and is intended only for the individual named.
If you are not the named addressee you should not disseminate, distribute or copy this e-mail.
Please notify the sender immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or
error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or
incomplete, or contain viruses. The sender therefore does not accept liability for any errors
or omissions in the contents of this message, which arise as a result of e-mail transmission.

**Comment by ch11ng** [comment]
Was the output created with the same DISPLAY (you may check the `DISPLAY` environment variable)?  If you're not sure, you can launch a terminal in EXWM and run `xrandr` there.  Also it can be helpful if you turn on `exwm-debug-on` and show us the `*Messages*` buffer.

**Comment by map7** [comment]
I've fixed the problem. My exwm randr settings where not getting loaded
as they are in an external file which was in the wrong location. So it's
working on my three screen thin client.

Regards,

Michael Pope
Programmer

Digitech Corporation
Ph +61 3 9642 4032

Disclaimer:
This message contains confidential information and is intended only for the individual named.
If you are not the named addressee you should not disseminate, distribute or copy this e-mail.
Please notify the sender immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or
error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or
incomplete, or contain viruses. The sender therefore does not accept liability for any errors
or omissions in the contents of this message, which arise as a result of e-mail transmission.

**Comment by ch11ng** [comment]
So I'm closing it.
