### ISSUE TITLE
make-network-process arguments for sockets changed in emacs 25

### ISSUE THREAD

**Issue by avoine** [ch11ng/xelb#14]
in xcb:connect-to-socket at https://github.com/ch11ng/xelb/blob/master/xcb.el#L186
I think make-network-process needs to have arguments:
<code>
 :family 'local :service socket
</code>
 instead of
<code>
 :remote socket
</code>

**Comment by ch11ng** [comment]
I'm not sure which Emacs version you were exactly referring, but for the current emacs-25 branch the address family is automatically recognized as `'local` when `:remote` is set to a string (see https://github.com/emacs-mirror/emacs/blob/emacs-25/src/process.c#L3184-L3196).  What's the advantage of using those two arguments?

**Comment by ch11ng** [comment]
Hi, since XELB seems to run well on Emacs up to version 27, I'm closing this issue now.
