### ISSUE TITLE
CreateRegion error when changing root pixmap

### ISSUE THREAD

**Issue by ghost** [ch11ng/xelb#17]
I don't really understand but EXWM shows this when I change the root pixmap:
[XELB ERROR] (invalid-slot-name "#<xcb:xfixes:CreateRegion :region>" 23329058)
emacs version 24.4.1, xelb commit d1d6b6cb48a6a9562252be20ab49f24708b34335 and exwm commit 7bc4ea5a6ee1d6d2948e8ba7e065be8ac33b8a47

It works as expected though.

**Comment by ch11ng** [comment]
Could you try out Emacs 25? XELB is designed using Emacs 25's object-oriented mechanism which is quite different from that of Emacs 24.

**Comment by ghost** [comment]
There's no error on Emacs 25. Since it's not fatal or anything on Emacs 24, should we just close this?

**Comment by ch11ng** [comment]
Fine.  It might be a problem of the cl-generic package.
