### ISSUE TITLE
void-function class-v

### ISSUE THREAD

**Issue by Sbozzolo** [ch11ng/xelb#18]
I am using Emacs 25.3.1 and I cannot update to `xelb` 0.13 as I get an error complaining about the `class-v` type:
```
(void-function class-v)
```

Best,
sbozzolo

**Comment by ch11ng** [comment]
`class-v` was an old macro from Emacs 24.  Please reinstall XELB and try again.

**Comment by Sbozzolo** [comment]
I tried `package-reinstall`, but it did not work. I had to manually delete the folder and reinstall it from scratch to not have Emacs complaining, and correctly compile everything.
