### ISSUE TITLE
(invalid-slot-name "#<xcb:SetupRequest xcb:SetupRequest>" cl-struct-cl-slot-descriptor)

### ISSUE THREAD

**Issue by rafoo** [ch11ng/xelb#21]
Hello and thank you for EXWM, I have been a very happy user of this window manager for two years.

I have just upgraded Emacs to version 25.1.1 and updated all my packages and unfortunately XELB and EXWM stopped working. Here is a recipe to reproduce the issue starting from `emacs -Q`:

```
(setq xcb:debug-on t)
(let ((default-directory "~/.emacs.d/elpa/"))
  (normal-top-level-add-subdirs-to-load-path))
(require 'xcb)
(xcb:connect)
```

Evaluating this snippet leads to the following error message: 
`Debugger entered--Lisp error: (invalid-slot-name "#<xcb:SetupRequest xcb:SetupRequest>" cl-struct-cl-slot-descriptor)`.

My machine runs Debian stable with XCB version 1.12.

**Comment by ch11ng** [comment]
Hi, are you upgrading from Emacs 24? It might have some compatibility issues with byte-compiled codes from an older release.  Please reinstall this package and try again.

**Comment by rafoo** [comment]
I was upgrading from Emacs 24 indeed. Reinstalling both EXWM and XELB solved the issue, thank you very much!
