### ISSUE TITLE
xelb-0.18 not found in elpa repo

### ISSUE THREAD

**Issue by izzatzr** [ch11ng/xelb#26]
`M-x package-install RET xelb RET`

Output:
`http://elpa.gnu.org/packages/xelb-0.18.tar: Not found` 

Emacs Version:
GNU Emacs 26.1

**Comment by ch11ng** [comment]
It seems to be there.  Could you try `wget http://elpa.gnu.org/packages/xelb-0.18.tar`?

**Comment by izzatzr** [comment]
> It seems to be there. Could you try `wget http://elpa.gnu.org/packages/xelb-0.18.tar`?

yes i can download with wget command, but i still got an error for installing the package using emacs. So should i install manually ??

**Comment by ch11ng** [comment]
Are you behind a proxy or something like that? Of course it's always fine to install the package manually.

**Comment by izzatzr** [comment]
no , im not behind proxy like you said . I remark this issue as solved , i consider to do manual install
