### ISSUE TITLE
xcb:keysyms:event->keysym fails

### ISSUE THREAD

**Issue by zevlg** [ch11ng/xelb#6]
If `xcb:keysyms:hyper-mask` is not set for some reason, then for example `(xcb:keysyms:event->keysym 16777330)` statement will throw an error like:

<pre>
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  logior(nil)
  apply(logior nil)
  (list keysym (apply (function logior) (mapcar (function (lambda (i) (cond ((eq i ...) (let nil xcb:keysyms:meta-mask)) ((eq i ...) (let nil xcb:keysyms:control-mask)) ((eq i ...) (let nil xcb:keysyms:shift-mask)) ((eq i ...) (let nil xcb:keysyms:hyper-mask)) ((eq i ...) (let nil xcb:keysyms:super-mask)) ((eq i ...) (let nil xcb:keysyms:alt-mask)) ((eq i ...) (let nil 0)) (t (let nil 0))))) modifiers)))
  (progn (list keysym (apply (function logior) (mapcar (function (lambda (i) (cond (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (t ...)))) modifiers))))
  (if keysym (progn (list keysym (apply (function logior) (mapcar (function (lambda (i) (cond ... ... ... ... ... ... ... ...))) modifiers)))))
  (let ((modifiers (event-modifiers event)) (event (event-basic-type event)) keysym) (if (not (integerp event)) (setq keysym (cond ((eq event (quote mouse-1)) (let nil xcb:ButtonIndex:1)) ((eq event (quote mouse-2)) (let nil xcb:ButtonIndex:2)) ((eq event (quote mouse-3)) (let nil xcb:ButtonIndex:3)) ((eq event (quote mouse-4)) (let nil xcb:ButtonIndex:4)) ((eq event (quote mouse-5)) (let nil xcb:ButtonIndex:5)) (t (let nil (if (setq keysym ...) (logior keysym 65280) (if ... ... ...)))))) (if (<= 32 event 255) (setq keysym event) (if (<= 256 event 1114111) (progn (setq keysym (+ 16777216 event)))))) (if keysym (progn (list keysym (apply (function logior) (mapcar (function (lambda ... ...)) modifiers))))))
  xcb:keysyms:event->keysym(16777330)
  (let ((xcb:keysyms:hyper-mask nil)) (xcb:keysyms:event->keysym 16777330))
  eval((let ((xcb:keysyms:hyper-mask nil)) (xcb:keysyms:event->keysym 16777330)) nil)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)
</pre>

**Comment by ch11ng** [comment]
Thanks, @zevlg. Fixed in c1d4e31abc7b9d1f8ff84231d285d73b39c5e0f3.
